fixtures:
  forge_modules:
    stdlib:       'puppetlabs/stdlib'
    powershell:   'puppetlabs/powershell'
    registry:     'puppetlabs/registry'
    ruby_task_helper: 'puppetlabs/ruby_task_helper'
  repositories:
      facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
      puppet_agent:
        repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
        ref: v4.13.0
      provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    chocolatey: "#{source_dir}"
