HOSTS:
  win-2008R2-std:
    roles:
      - default
      - agent
    platform: windows-server-amd64
    box: opentable/win-2008r2-standard-amd64-nocm
    hypervisor: vagrant
    user: vagrant
CONFIG:
  log_level: verbose
  type: git